version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"     # Porta para aplicações (AMQP)
      - "15672:15672"   # Painel web

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - rabbitmq_net
      
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

networks:
  rabbitmq_net:
    driver: bridge
